logging:
  level:
    com.averygrimes.secretschest: INFO
  file.path: logs/secrets-chest-log

server:
  error:
    include-stacktrace: always

server.servlet.context-path: /secrets-chest-service
server.port: 6570